### ISSUE TITLE
Regarding Modification of Functions

### ISSUE THREAD

**Issue by mdhchan** [HPCE/hpce-2017-cw5#16]
I understand that we are only supposed to change Execute, but is it possible for us to modify or override functions used within the execute function?  For instance, MakeProjection() in random projection.

**Comment by m8pple** [comment]
In your provider class you can do whatever you want, so you can define new versions of MakeProjection, or eliminate that function completely.  However you should leave the original puzzle class as is. 

Don't feel constrained by the original form of reference execute - Your version could look similar, or be completely different with new functions that weren't in the original.
