### ISSUE TITLE
heat_world bug?

### ISSUE THREAD

**Issue by thomasrarris** [HPCE/hpce-2017-cw5#17]
In the heat_world puzzle, at the end of the `ReferenceExecute` function, the instruction `buffer[index] = res;` is missing after `res=std::min(1.0f, std::max(-1.0f, res));`.

**Comment by m8pple** [comment]
Thanks for that - I have to admit that for heat world I didn't actually
look at the output in detail, which is pretty much going against everything
I've claimed about testing.
