### ISSUE TITLE
random_projection output is just zeros

### ISSUE THREAD

**Issue by jacekburys** [HPCE/hpce-2017-cw5#20]
It seems that for an input bigger than 16, random_projection produces output which is just a vector filled with zeros. Is this expected? In this case are we expected to check the correctness using small inputs and then evaluate the speedup for large inputs?

**Comment by m8pple** [comment]
I think this is the same problem as in #9 

Can you check that you're on the latest version of the repo?

**Comment by jacekburys** [comment]
I pulled the latest version of the repo and the problem is gone. Thanks!
