### ISSUE TITLE
g2.2xlarge instance not launching in aws

### ISSUE THREAD

**Issue by crypto-perry** [HPCE/hpce-2017-cw5#24]
![screen shot 2017-11-15 at 11 30 09 pm](https://user-images.githubusercontent.com/11064339/32865890-06019f2a-ca5d-11e7-9cf6-56bcad462174.png)
 I get that when I try to launch the instance. Anyone getting the same? I already followed their advice and asked to raise the limit but what if that doesn't happen in due time.

**Comment by guigzzz** [comment]
It doesn't seem we have access to GPU instances using our AWS educate account. At least when I try to launch an instance, I cannot select a GPU instance.

**Comment by m8pple** [comment]
I think they usually raise the limit reasonably quickly - if you've spent some time launching
other AWS instances, then they usually either don't impose the limit. Assuming everyone
tried to start a g2.2xlarge for CW3, they will usually have allowed it by now.

So this only happens for `g2.2xlarge` - the c4.8xlarge was ok for CW4?

They are generally suspicious of accounts that are created and then people immediately try
to go for the bigger/more expensive instances, as it could be people who have got a stolen
credit card or something. They are also sensitive to GPU instances, as people try to use
throwaway or stolen accounts to do bit-coin mining.

**Comment by davidpasztor** [comment]
Even normal AWS accounts have a limit on the number of instances you can run simultaneously and the default limit for g2.2xlarge instances is set to 0 by default.
You can request a limit increase in the Limits tab.
![Limits](https://image.prntscr.com/image/1xNqu6c8QdSsfo0CZRo4cA.png)
For me it took a few days for them to approve the limit increase.

**Comment by m8pple** [comment]
@guigzzz Is this for a standard AWS Account with AWS Educate credits (the $100 grant),
or for an AWS Educate Starter Account (the limited one with $75).

You should be able to start GPU instances using the normal AWS account, but may need
to request an increase to your account limits (which can take a couple of days).

**Comment by m8pple** [comment]
Ah, thanks @davidpasztor - I think when I first used AWS they were more generous,
and you could start up to 1 g2.2xlarge by default as long as you'd been using it
for a bit.

**Comment by guigzzz** [comment]
@m8pple I realise now that I was simply looking at the wrong region (London doesn't have gpu instances apparently). Once I set the region to something like North Virginia everything's fine (although I still need to request a limit increase on the g2.2xlarge instance).

[this](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-resource-limits.html) should help anyone else trying to request an increase.

**Comment by crypto-perry** [comment]
I got my limit increased to 3 in 2 days so people should start requesting early

**Comment by JB515** [comment]
Interesting case here, my g2.2xlarge limit started at 5, which I still have, but I get a permission error when I try to launch one.

![capture](https://user-images.githubusercontent.com/15146290/33025321-8a330e40-ce05-11e7-9653-0a1adeef2809.JPG)

**Comment by m8pple** [comment]
Odd - is that repeatable if you explicitly log out of AWS and back in again?

I've seen it in the context of IAM roles, but not when logged in as myself.

**Comment by JB515** [comment]
Yes, logging in and out doesn't make any difference.

**Comment by m8pple** [comment]
Afraid I couldn't find any more information or suggestions on it - it might need
to be escalated to EC2 support.

Presumably your partner(s) are able to launch them, so you're ok for now.
