### ISSUE TITLE
Possible typo  ?

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw5#27]
In readme.md 
**" If a puzzle runs too long and is terminated, it does not count as being incorrect."**

@m8pple , could you kindly clarify this ?

**Comment by m8pple** [comment]
Given there is a limited time budget, and the scale just increases without end, the very
last puzzle instance that people solve will always be cut-off. If this was counted as incorrect,
then everyone would be guaranteed one incorrect result per puzzle, which isn't fair. In
a halting problem sense, a puzzle that has not yet finished is neither correct nor incorrect.
