### ISSUE TITLE
target platform 

### ISSUE THREAD

**Issue by janscholten** [HPCE/hpce-2017-cw5#28]
According to the readme our code will be benchmarked on a `g2.2xlarge` instance. It occurs to me that this one is not listed in AWS. It could be that it has been replaced (or am I not looking in the right place) If it has been replaced, what would be the designated platform this year? Or, where can I find and launch the g2.2xlarge?

**Comment by benfwalker** [comment]
Duplicate of #24

**Comment by janscholten** [comment]
thank you, sorry for that
