### ISSUE TITLE
makefile issues

### ISSUE THREAD

**Issue by pufik1337** [HPCE/hpce-2017-cw5#3]
A small part of the makefile was probably not updated for this year:
 1. no input file is specified for bin/compare_puzzle_output when the target is serenity_now_% - this causes segfaults
 2. the serenity_now target refers to puzzles from last year

These changes fix the issues on my side:
```
serenity_now_% : all
	mkdir -p w
	bin/run_puzzle $* 100 2
	bin/create_puzzle_input $* 100 2 > w/$*.in
	cat w/$*.in | bin/execute_puzzle 1 2 > w/$*.ref.out
	cat w/$*.in | bin/execute_puzzle 0 2 > w/$*.got.out
	bin/compare_puzzle_output w/$*.in w/$*.ref.out w/$*.got.out 2

serenity_now : $(foreach x,mining heat_world gaussian_blur edit_distance random_projection hold_time,serenity_now_$(x))
```

**Comment by m8pple** [comment]
Yes, I'd completely forgotten to actually read the makefile, as I was just driving
from the command line. So I'll take the out all the Julia stuff, and modify
"serenity now" as suggested (apparently I was watching Seinfeld at this time last year).
