### ISSUE TITLE
Performance benchmark plot y-axis

### ISSUE THREAD

**Issue by TheoFranquet** [HPCE/hpce-2017-cw5#34]
Regarding the plots of individual puzzle execution performance, is the y-axis really in milliseconds?
As of now it looks like large problems are getting solved in matters of microseconds.

Is the y-axis scale arbitrary?

**Comment by m8pple** [comment]
The intent of the graph is more to look at scaling and relative performance, so the times
are kind of arbitrary - the question mark is a bit of a joke from last year I think, that should
probably be fixed.

You can see the raw data in the log files and the csv files, which are all in seconds.
