### ISSUE TITLE
Is the makefile out of date?

### ISSUE THREAD

**Issue by BaronKhan** [HPCE/hpce-2017-cw5#4]
In the top level directory, the makefile contains the following build target:

```
serenity_now : $(foreach x,julia ising_spin logic_sim random_walk,serenity_now_$(x))
```
This would build and execute the reference and our versions for puzzles, "julia", "ising_spin", etc. Looking at the 2016 version, these were the puzzles used in that. Does this mean the makefile may be out of date?

**Comment by BaronKhan** [comment]
Closing because pufik1337 beat me by six minutes: https://github.com/HPCE/hpce-2017-cw5/issues/3

**Comment by m8pple** [comment]
But it's still appreciated :)
