### ISSUE TITLE
[Comedy] Not an issue, but I found this funny

### ISSUE THREAD

**Issue by paulbalaji** [HPCE/hpce-2017-cw5#40]
![image](https://user-images.githubusercontent.com/10051819/33050567-65702d10-ce5d-11e7-9d1f-f998f2b1ec30.png)

**Comment by m8pple** [comment]
I was visiting Seattle a couple of years ago for Christmas, and mentioned the TEA hash
in passing to someone, and they looked at me oddly and then said, so you mean "hash tea?".
(Seattle has quite liberal laws...)
