### ISSUE TITLE
Possible change of coeff() in gaussian_blur

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw5#43]
Hi,

@m8pple - Can we assume that the definition of this function - 

```
 double coeff(int dx, int dy, double r) const
    {
      return exp(- (dx*dx+dy*dy) / (2*r) ) / (2 * 3.1415926535897932384626433832795 * r);
    }
```

will remain the same when our code is tested. One simple reason may be that our implementation may not call this function, but something similar in order to achieve our goal. If the definition of this function were to change, then it would render my custom function incorrect.

Thanks!

**Comment by m8pple** [comment]
Yes, you can assume it will be the same. As it is inside the puzzle class,
it is part of the defined behavior of the puzzle, and cannot be changed.

So feel free to pull it apart or do whatever else you want with it.
