### ISSUE TITLE
std::chrono not found on instance

### ISSUE THREAD

**Issue by ghr55** [HPCE/hpce-2017-cw5#61]
I've been using high precision timer to time my executes on my computer. However, when trying to use the timer on the AWS instance, I got errors that std::chrono wasn't recognised. Any ideas as to why that may be?

**Comment by m8pple** [comment]
As far as I know, it should be present, as the compiler supports c++11 and it is
part of the c++11 standard.

What are the errors that you are seeing?

**Comment by ghr55** [comment]
I went on AWS again yesterday and this time didn't get an error. Not sure what the issue was but doesn't seem to be there anymore.
